### PR TITLE
Improve installation instructions

### PR DESCRIPTION
**Pull request by Bananeweizen**
If people stumble into the update site with a normal browser, they should be instructed to head over to the main repository for reading instructions.

### CODE REVIEW

**Review by rnveach — CHANGES_REQUESTED** [review]
> If people stumble into the update site with a normal browser

Changing a readme file will not help this except if they are only looking at github and not https://checkstyle.org/ . If you want people in a browser to see this when they go to the directory at https://checkstyle.org/ , you need to add an `index.html` file in the directory your targeting.

See https://github.com/sevntu-checkstyle/sevntu.checkstyle/issues/857
and https://github.com/sevntu-checkstyle/sevntu.checkstyle/blob/gh-pages/update-site/index.html
and https://sevntu-checkstyle.github.io/sevntu.checkstyle/update-site/

**Comment by Bananeweizen** [comment]
That readme is what people see if they currently visit one of:
https://github.com/checkstyle/eclipse-cs-update-site
https://checkstyle.org/eclipse-cs-update-site/

Therefore it should be merged IMO. Nevertheless you are right in that adding an explicit index.html to the repo is probably even better since that would lead to much better content for the second of the 2 URLs.

**Review by rnveach — APPROVED** [review]
Maybe there is something going on that converts the readme to an actual page as that is normal for HTTP.

Edit: I would be worried that maybe this process may overwrite your custom `index.html`.

**Comment by Bananeweizen** [comment]
Quite honestly, I also have no idea how GitHub works there. But if I were the engineer implementing it, I would only use the readme with secondary priority after using existing index.htm(l). Just one way to test: someone needs to merge it (I can't). :)

**Comment by rnveach** [comment]
@Calixte ping

Please review and merge if you are good.

**Comment by Calixte** [comment]
I merged.
As expected, the index.html took over and replaced the README.md file at http://checkstyle.org/eclipse-cs-update-site/
I feel like we could put all necessary info in the README.md and just use that, so we don't have to maintain the index.html.

**Pull request merged**
